"""PySide6 tray popup and Pillow system-tray icon."""

from __future__ import annotations

from dataclasses import dataclass

from PIL import Image, ImageDraw, ImageFont
from PySide6.QtCore import QRectF, Qt, QTimer
from PySide6.QtGui import QColor, QFontMetrics, QPainter, QPen, QRadialGradient
from PySide6.QtWidgets import QApplication, QLabel, QPushButton, QWidget

from . import i18n, ui_colors
from .config import resource_dir
from .floating_ui_qt import (
    ScreenGeometry,
    WindowRect,
    _cursor_position,
    _dpi_scale,
    _font,
    _force_topmost,
    _hide_from_taskbar,
    _native_window_size,
    _reapply_icon_after_show,
    _screen_geometry,
    _set_native_geometry,
    _window_icon,
    work_area_for_point,
)


WINDOW_WIDTH = 300
WINDOW_HEIGHT = 233
COLLAPSED_HEIGHT = 169
CORNER_RADIUS = 14
TRAY_EDGE_MARGIN = 7


@dataclass(frozen=True)
class CursorPosition:
    x: int
    y: int


def read_cursor_position() -> CursorPosition:
    x, y = _cursor_position()
    return CursorPosition(x, y)


def _screen_entry_for_cursor(
    cursor: CursorPosition,
):
    app = QApplication.instance()
    if app is None:
        raise RuntimeError("TrayPopup requires an active QApplication")

    entries = tuple(
        (screen, _screen_geometry(screen))
        for screen in app.screens()
    )
    if not entries:
        raise RuntimeError("Qt reported no screens")

    for entry in entries:
        _, geometry = entry
        width_scale, height_scale = _dpi_scale(geometry)
        left = round(geometry.x * width_scale)
        top = round(geometry.y * height_scale)
        right = left + round(geometry.width * width_scale)
        bottom = top + round(geometry.height * height_scale)

        if (
            left <= cursor.x < right
            and top <= cursor.y < bottom
        ):
            return entry

    def distance_squared(entry) -> int:
        _, geometry = entry
        width_scale, height_scale = _dpi_scale(geometry)
        left = round(geometry.x * width_scale)
        top = round(geometry.y * height_scale)
        right = left + round(geometry.width * width_scale)
        bottom = top + round(geometry.height * height_scale)

        nearest_x = min(max(cursor.x, left), right - 1)
        nearest_y = min(max(cursor.y, top), bottom - 1)
        return (
            (cursor.x - nearest_x) ** 2
            + (cursor.y - nearest_y) ** 2
        )

    return min(entries, key=distance_squared)


def _target_bottom_right(work_area: WindowRect):
    def target(rect: WindowRect) -> tuple[int, int]:
        return (
            work_area.right - TRAY_EDGE_MARGIN - rect.width,
            work_area.bottom - TRAY_EDGE_MARGIN - rect.height,
        )

    return target


def _bar_percentage(value, connected: bool) -> float:
    if value is None or not connected:
        return 0
    return max(0, min(100, float(value)))


_ICON_FONT_PATH = resource_dir() / "assets" / "Inconsolata-Bold.ttf"


def make_icon_image(color: str, size: int = 32):
    """The Se7e mark: a dark rounded badge with a bold "7", tinted by
    whatever color the caller already uses for live status (unlike the old
    plain dot, this is a badge with the same color-as-status behavior).

    ``size`` defaults to 32 for the system-tray icon (pystray's native
    resolution, no scaling involved). The window-icon .ico, shown in the
    taskbar/Alt-Tab at much larger sizes, is instead generated by calling
    this at a large size (e.g. 256) and letting Pillow's ICO writer
    downscale — downscaling a crisp large source looks sharp everywhere;
    upscaling a small one (the original bug here) looks pixelated.
    """
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    margin = max(1, round(size / 32))
    draw.rounded_rectangle(
        (
            margin,
            margin,
            size - 1 - margin,
            size - 1 - margin,
        ),
        radius=round(size / 4),
        fill="#14161c",
    )
    try:
        font = ImageFont.truetype(
            str(_ICON_FONT_PATH),
            round(size * 21 / 32),
        )
    except OSError:
        font = ImageFont.load_default()

    text = "7"
    left, top, right, bottom = draw.textbbox(
        (0, 0),
        text,
        font=font,
    )
    x = (size - (right - left)) / 2 - left
    y = (size - (bottom - top)) / 2 - top
    draw.text((x, y), text, font=font, fill=color)
    return img


THEMES = {
    "dark": {
        "background": "#14161c",
        "border": "#262a35",
        "track": "#232733",
        "week_fill": "#3f4657",
        "primary": "#e7e9ee",
        "secondary": "#a8adba",
        "muted": "#6b7280",
        "button_background": "#1c1f27",
        "button_text": "#cdd1db",
        "claude_fill": "#22c55e",
        "codex_fill": "#38bdf8",
    },
    "light": {
        "background": "#f5f6f8",
        "border": "#dcdfe4",
        "track": "#e4e7ec",
        "week_fill": "#b8bfc9",
        "primary": "#1a1d24",
        "secondary": "#4b5160",
        "muted": "#8b93a1",
        "button_background": "#e9ebef",
        "button_text": "#2a2d35",
        "claude_fill": "#16a34a",
        "codex_fill": "#0284c7",
    },
}


class _ProviderRow(QWidget):
    def __init__(
        self,
        provider_name: str,
        popup: "TrayPopup",
        parent: QWidget,
    ) -> None:
        super().__init__(parent)
        self.provider_name = provider_name
        self.popup = popup
        self.setAttribute(
            Qt.WidgetAttribute.WA_TransparentForMouseEvents,
            True,
        )

    def _draw_dot(
        self,
        painter: QPainter,
        color_text: str,
        visible: bool,
    ) -> None:
        if not visible:
            return

        # Shifted +4px right vs. the original (-4, -2, 16, 16) glow / (0, 2, 8, 8)
        # dot: a widget's own paintEvent clips anything drawn at a negative
        # local coordinate (it's outside that widget's own backing store,
        # even though it'd geometrically fit inside the parent) — the glow's
        # left sliver was disappearing, looking like clipped/cut-off content.
        color = QColor(color_text)
        glow = QRadialGradient(8, 6, 8)
        glow_color = QColor(color)
        glow_color.setAlpha(150)
        transparent = QColor(color)
        transparent.setAlpha(0)
        glow.setColorAt(0.35, glow_color)
        glow.setColorAt(1.0, transparent)

        painter.setPen(Qt.PenStyle.NoPen)
        painter.setBrush(glow)
        painter.drawEllipse(QRectF(0, -2, 16, 16))
        painter.setBrush(color)
        painter.drawEllipse(QRectF(4, 2, 8, 8))

    def _draw_bar(
        self,
        painter: QPainter,
        top: int,
        label: str,
        percentage: float,
        text: str,
        fill_color: str,
        bold: bool,
    ) -> None:
        colors = THEMES[self.popup.theme]

        painter.setFont(_font(8))
        painter.setPen(QColor(colors["muted"]))
        painter.drawText(
            QRectF(0, top, 18, 12),
            Qt.AlignmentFlag.AlignVCenter
            | Qt.AlignmentFlag.AlignLeft,
            label,
        )

        track = QRectF(22, top + 4, 182, 4)
        painter.setPen(Qt.PenStyle.NoPen)
        painter.setBrush(QColor(colors["track"]))
        painter.drawRoundedRect(track, 2, 2)

        fill_width = track.width() * percentage / 100
        if fill_width > 0:
            painter.setBrush(QColor(fill_color))
            painter.drawRoundedRect(
                QRectF(
                    track.left(),
                    track.top(),
                    fill_width,
                    track.height(),
                ),
                2,
                2,
            )

        font = _font(9, bold=bold)
        metrics = QFontMetrics(font)
        # Wide enough for the longest real value here — "não conectado"/
        # "not connected" (59px measured with this font) — with a few
        # pixels to spare; a narrower column used to elide it down to a
        # nonsensical "...o conectado".
        available_width = self.width() - 208
        display_text = metrics.elidedText(
            text,
            Qt.TextElideMode.ElideLeft,
            max(1, available_width),
        )

        painter.setFont(font)
        painter.setPen(QColor(colors["primary"]))
        painter.drawText(
            QRectF(208, top, available_width, 12),
            Qt.AlignmentFlag.AlignVCenter
            | Qt.AlignmentFlag.AlignRight,
            display_text,
        )

    def paintEvent(self, event) -> None:
        del event

        colors = THEMES[self.popup.theme]
        state = self.popup._provider_state(self.provider_name)

        painter = QPainter(self)
        painter.setRenderHint(
            QPainter.RenderHint.Antialiasing,
            True,
        )

        self._draw_dot(
            painter,
            state["dot_color"],
            not state["blink"] or self.popup._blink_on,
        )

        strings = i18n.STRINGS.get(
            self.popup.lang,
            i18n.STRINGS[i18n.DEFAULT_LANGUAGE],
        )
        provider_label = (
            strings["provider_claude_full"]
            if self.provider_name == "claude"
            else strings["provider_codex"]
        )

        painter.setFont(_font(10))
        painter.setPen(QColor(colors["secondary"]))
        painter.drawText(
            QRectF(18, 0, self.width() - 18, 12),
            Qt.AlignmentFlag.AlignVCenter
            | Qt.AlignmentFlag.AlignLeft,
            provider_label,
        )

        primary_fill = (
            colors["claude_fill"]
            if self.provider_name == "claude"
            else colors["codex_fill"]
        )

        self._draw_bar(
            painter,
            15,
            strings["popup_label_5h"],
            state["five_hour_percentage"],
            state["five_hour_text"],
            primary_fill,
            True,
        )
        self._draw_bar(
            painter,
            28,
            strings["popup_label_week"],
            state["week_percentage"],
            state["week_text"],
            colors["week_fill"],
            False,
        )


class _TrayPanel(QWidget):
    def __init__(self, popup: "TrayPopup") -> None:
        super().__init__()
        self.popup = popup

        self.setWindowTitle(popup.title)
        self.setWindowFlags(
            Qt.WindowType.Window
            | Qt.WindowType.FramelessWindowHint
            | Qt.WindowType.WindowStaysOnTopHint
        )
        self.setAttribute(
            Qt.WidgetAttribute.WA_TranslucentBackground,
            True,
        )
        self.setAttribute(
            Qt.WidgetAttribute.WA_DeleteOnClose,
            False,
        )

        self.title_label = QLabel(self)
        self.updated_label = QLabel(self)
        self.reload_button = QPushButton("↻", self)  # universal reload glyph, not translated

        self.claude_row = _ProviderRow(
            "claude",
            popup,
            self,
        )
        self.codex_row = _ProviderRow(
            "codex",
            popup,
            self,
        )

        self.collapse_button = QPushButton(self)
        self.floating_button = QPushButton(self)
        self.transparent_button = QPushButton(self)
        self.hide_button = QPushButton(self)
        self.quit_button = QPushButton(self)

        self.collapse_button.clicked.connect(
            popup.toggle_actions
        )
        self.floating_button.clicked.connect(
            popup._on_toggle_floating
        )
        self.transparent_button.clicked.connect(
            popup._on_toggle_transparent
        )
        self.hide_button.clicked.connect(popup.hide)
        self.quit_button.clicked.connect(popup._on_quit)
        self.reload_button.clicked.connect(popup._on_reload_usage)

        self._set_geometry()
        self.apply_theme()
        self.apply_translations()
        self.refresh()
        # Set last, right before this window is shown by the caller: with
        # this many child widgets, construction takes long enough that
        # Windows' shell can query (and cache, for this AppUserModelID
        # group) the taskbar icon before it was set, if set earlier —
        # observed live: whichever window opens first "wins" the group's
        # icon for the rest of the session.
        self.setWindowIcon(_window_icon())

    def _set_geometry(self) -> None:
        self.title_label.setGeometry(14, 14, 100, 14)
        # Narrower than before (was 172) to make room for reload_button —
        # only visible while stale, so it sits right after the text with
        # no gap when hidden.
        self.updated_label.setGeometry(114, 14, 154, 14)
        self.reload_button.setGeometry(270, 11, 16, 16)

        self.claude_row.setGeometry(14, 45, 272, 39)
        self.codex_row.setGeometry(14, 88, 272, 39)

        self.collapse_button.setGeometry(14, 129, 272, 24)

        self.floating_button.setGeometry(14, 157, 134, 28)
        self.transparent_button.setGeometry(152, 157, 134, 28)
        self.hide_button.setGeometry(14, 189, 134, 28)
        self.quit_button.setGeometry(152, 189, 134, 28)

    def apply_theme(self) -> None:
        colors = THEMES[self.popup.theme]

        self.title_label.setStyleSheet(
            f"color: {colors['secondary']}; background: transparent;"
        )
        self.updated_label.setStyleSheet(
            f"color: {colors['muted']}; background: transparent;"
        )

        self.title_label.setFont(_font(11, bold=True))
        self.updated_label.setFont(_font(9))
        self.title_label.setAlignment(
            Qt.AlignmentFlag.AlignVCenter
            | Qt.AlignmentFlag.AlignLeft
        )
        self.updated_label.setAlignment(
            Qt.AlignmentFlag.AlignVCenter
            | Qt.AlignmentFlag.AlignRight
        )

        # Only :hover, not :focus — a clicked QPushButton keeps keyboard
        # focus afterward (normal Qt behavior), and styling :focus the same
        # as :hover made every button look permanently "stuck" highlighted
        # after being clicked, until something else happened to steal
        # focus. These are mouse-driven tray buttons with no need to
        # participate in focus/tab order at all (see setFocusPolicy below),
        # so :focus isn't styled here rather than styled differently.
        button_style = f"""
            QPushButton {{
                border: none;
                border-radius: 6px;
                padding: 0 6px;
                background: {colors["button_background"]};
                color: {colors["button_text"]};
            }}
            QPushButton:hover {{
                background: {colors["border"]};
                outline: none;
            }}
        """

        for button in (
            self.floating_button,
            self.transparent_button,
            self.hide_button,
            self.quit_button,
        ):
            button.setFont(_font(9))
            button.setStyleSheet(button_style)
            button.setFocusPolicy(Qt.FocusPolicy.NoFocus)

        self.collapse_button.setFont(_font(20))
        self.collapse_button.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.collapse_button.setStyleSheet(
            f"""
            QPushButton {{
                border: none;
                background: transparent;
                color: {colors["muted"]};
            }}
            QPushButton:hover {{
                color: {colors["secondary"]};
            }}
            """
        )

        self.reload_button.setFont(_font(11))
        self.reload_button.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.reload_button.setStyleSheet(
            f"""
            QPushButton {{
                border: none;
                background: transparent;
                color: {colors["muted"]};
                padding: 0;
            }}
            QPushButton:hover {{
                color: {colors["secondary"]};
            }}
            """
        )

        self.claude_row.update()
        self.codex_row.update()
        QWidget.update(self)

    def apply_translations(self) -> None:
        strings = i18n.STRINGS.get(
            self.popup.lang,
            i18n.STRINGS[i18n.DEFAULT_LANGUAGE],
        )

        self.title_label.setText(strings["popup_title"])
        self.floating_button.setText(
            strings["popup_btn_floating"]
        )
        self.transparent_button.setText(
            strings["popup_btn_transparent"]
        )
        self.hide_button.setText(strings["popup_btn_hide"])
        self.quit_button.setText(strings["popup_btn_quit"])
        self.reload_button.setToolTip(strings["popup_btn_reload_usage"])

        self.claude_row.update()
        self.codex_row.update()

    def set_actions_visible(self, visible: bool) -> None:
        for button in (
            self.floating_button,
            self.transparent_button,
            self.hide_button,
            self.quit_button,
        ):
            button.setVisible(visible)

        self.collapse_button.setText("▴" if visible else "▾")

    def refresh(self) -> None:
        self.updated_label.setText(
            self.popup._state["updated_text"]
        )
        self.reload_button.setVisible(
            self.popup._state["stale"]
        )
        self.set_actions_visible(
            self.popup._actions_expanded
        )
        self.claude_row.update()
        self.codex_row.update()
        QWidget.update(self)

    def paintEvent(self, event) -> None:
        del event

        colors = THEMES[self.popup.theme]
        painter = QPainter(self)
        painter.setRenderHint(
            QPainter.RenderHint.Antialiasing,
            True,
        )

        background = QColor(colors["background"])
        if self.popup._transparent:
            background.setAlphaF(0.7)

        outer = QRectF(
            0.5,
            0.5,
            self.width() - 1,
            self.height() - 1,
        )
        painter.setPen(Qt.PenStyle.NoPen)
        painter.setBrush(background)
        painter.drawRoundedRect(
            outer,
            CORNER_RADIUS,
            CORNER_RADIUS,
        )

        painter.setBrush(Qt.BrushStyle.NoBrush)
        painter.setPen(QPen(QColor(colors["border"]), 1))
        painter.drawRoundedRect(
            outer,
            CORNER_RADIUS,
            CORNER_RADIUS,
        )

        painter.setPen(QPen(QColor(colors["track"]), 1))
        painter.drawLine(14, 36, 286, 36)


class TrayPopup:
    def __init__(
        self,
        on_toggle_floating,
        on_toggle_transparent,
        on_quit,
        on_reload_usage=None,
        title: str = "Se7e",
        lang: str = i18n.DEFAULT_LANGUAGE,
        theme: str = "dark",
    ) -> None:
        self.title = title
        self.lang = lang
        self.theme = theme if theme == "light" else "dark"

        self.window: _TrayPanel | None = None
        self.positioning = None
        self.screen_geometry: ScreenGeometry | None = None
        self._visible = False
        self._transparent = False
        self._actions_expanded = True
        self._blink_on = True

        self._on_toggle_floating = on_toggle_floating
        self._on_toggle_transparent = on_toggle_transparent
        self._on_quit = on_quit
        self._on_reload_usage = on_reload_usage or (lambda: None)

        self._state = {
            "claude_status": "parado",
            "claude_5h": None,
            "claude_week": None,
            "claude_connected": True,
            "codex_status": "parado",
            "codex_5h": None,
            "codex_week": None,
            "codex_connected": True,
            "updated_text": "atualizado ha --s",
            "stale": False,
        }

        self._blink_timer: QTimer | None = None

    def _provider_state(self, name: str) -> dict:
        status = self._state[f"{name}_status"]
        connected = self._state[f"{name}_connected"]
        five_hour = self._state[f"{name}_5h"]
        week = self._state[f"{name}_week"]

        working_color = (
            ui_colors.CLAUDE_WORKING_COLOR
            if name == "claude"
            else ui_colors.CODEX_WORKING_COLOR
        )

        return {
            "dot_color": ui_colors.color_for_status(
                status,
                working_color=working_color,
                connected=connected,
            ),
            "blink": ui_colors.should_blink(
                status,
                connected=connected,
            ),
            "five_hour_percentage": _bar_percentage(
                five_hour,
                connected,
            ),
            "five_hour_text": ui_colors.format_pct(
                five_hour,
                connected,
                lang=self.lang,
            ),
            "week_percentage": _bar_percentage(
                week,
                connected,
            ),
            "week_text": ui_colors.format_pct(
                week,
                connected,
                lang=self.lang,
            ),
        }

    def _advance_blink(self) -> None:
        claude = self._provider_state("claude")
        codex = self._provider_state("codex")

        if claude["blink"] or codex["blink"]:
            self._blink_on = not self._blink_on
        else:
            self._blink_on = True

        if self.window is not None:
            self.window.claude_row.update()
            self.window.codex_row.update()

    def _ensure_blink_timer(self) -> None:
        if self._blink_timer is not None:
            return

        self._blink_timer = QTimer()
        self._blink_timer.setInterval(300)
        self._blink_timer.timeout.connect(self._advance_blink)
        self._blink_timer.start()

    def set_language(self, lang: str) -> None:
        self.lang = (
            lang
            if lang in i18n.SUPPORTED_LANGUAGES
            else i18n.DEFAULT_LANGUAGE
        )
        if self.window is not None:
            self.window.apply_translations()
            self.window.refresh()

    def set_theme(self, theme: str) -> None:
        self.theme = "light" if theme == "light" else "dark"
        if self.window is not None:
            self.window.apply_theme()
            self.window.refresh()

    def _cursor_placement(
        self,
        height: int = WINDOW_HEIGHT,
    ):
        cursor = read_cursor_position()
        screen, screen_geometry = _screen_entry_for_cursor(cursor)
        work_area = work_area_for_point(cursor.x, cursor.y)

        physical_width, physical_height = _native_window_size(
            WINDOW_WIDTH,
            height,
            screen_geometry,
        )
        nominal_rect = WindowRect(
            0,
            0,
            physical_width,
            physical_height,
        )
        target_position = _target_bottom_right(work_area)
        x, y = target_position(nominal_rect)

        return (
            screen,
            screen_geometry,
            x,
            y,
            physical_width,
            physical_height,
        )

    def _resize_and_reposition(self, height: int) -> None:
        if self.window is None:
            return

        (
            _screen,
            screen_geometry,
            x,
            y,
            physical_width,
            physical_height,
        ) = self._cursor_placement(height)

        self.screen_geometry = screen_geometry
        self.window.setFixedSize(WINDOW_WIDTH, height)
        _set_native_geometry(
            self.window,
            x,
            y,
            physical_width,
            physical_height,
        )
        self.positioning = WindowRect(
            x,
            y,
            x + physical_width,
            y + physical_height,
        )
        _force_topmost(self.window)

    def _build(self) -> None:
        self._actions_expanded = True
        self.window = _TrayPanel(self)
        self._ensure_blink_timer()
        self._resize_and_reposition(WINDOW_HEIGHT)
        _hide_from_taskbar(self.window)
        self.window.show()
        _reapply_icon_after_show(self.window)
        self.window.raise_()
        self.window.activateWindow()
        _force_topmost(self.window)
        self._visible = True

    def _show_near_cursor(self) -> None:
        if self.window is None:
            return

        self._actions_expanded = True
        self.window.set_actions_visible(True)
        self._resize_and_reposition(WINDOW_HEIGHT)
        self.window.show()
        self.window.raise_()
        self.window.activateWindow()
        _force_topmost(self.window)
        self._visible = True

    def toggle_actions(self) -> None:
        if self.window is None:
            return

        self._actions_expanded = not self._actions_expanded
        self.window.set_actions_visible(
            self._actions_expanded
        )
        height = (
            WINDOW_HEIGHT
            if self._actions_expanded
            else COLLAPSED_HEIGHT
        )
        self._resize_and_reposition(height)
        self.window.refresh()

    def toggle(self) -> None:
        if self.window is None:
            self._build()
        elif self._visible:
            self.hide()
        else:
            self._show_near_cursor()

    def hide(self) -> None:
        if self.window is not None and self._visible:
            self.window.hide()
            self._visible = False

    def update(
        self,
        claude_status,
        claude_5h,
        claude_week,
        codex_status,
        codex_5h,
        codex_week,
        updated_text,
        claude_connected: bool = True,
        codex_connected: bool = True,
        stale: bool = False,
    ) -> None:
        self._state.update(
            claude_status=claude_status,
            claude_5h=claude_5h,
            claude_week=claude_week,
            claude_connected=claude_connected,
            codex_status=codex_status,
            codex_5h=codex_5h,
            codex_week=codex_week,
            codex_connected=codex_connected,
            updated_text=updated_text,
            stale=stale,
        )

        if self.window is not None:
            self.window.refresh()

    def set_transparent(self, enabled: bool) -> None:
        self._transparent = bool(enabled)
        if self.window is not None:
            QWidget.update(self.window)

    def destroy(self) -> None:
        if self._blink_timer is not None:
            self._blink_timer.stop()
            self._blink_timer.deleteLater()
            self._blink_timer = None

        if self.window is not None:
            self.window.close()
            self.window.deleteLater()
            self.window = None

        self._visible = False
